// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cstkpk/dictionary/api/models"
)

// GetDefinitionOKCode is the HTTP code returned for type GetDefinitionOK
const GetDefinitionOKCode int = 200

/*GetDefinitionOK Success

swagger:response getDefinitionOK
*/
type GetDefinitionOK struct {

	/*
	  In: Body
	*/
	Payload *models.Definition `json:"body,omitempty"`
}

// NewGetDefinitionOK creates GetDefinitionOK with default headers values
func NewGetDefinitionOK() *GetDefinitionOK {

	return &GetDefinitionOK{}
}

// WithPayload adds the payload to the get definition o k response
func (o *GetDefinitionOK) WithPayload(payload *models.Definition) *GetDefinitionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get definition o k response
func (o *GetDefinitionOK) SetPayload(payload *models.Definition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDefinitionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDefinitionNotFoundCode is the HTTP code returned for type GetDefinitionNotFound
const GetDefinitionNotFoundCode int = 404

/*GetDefinitionNotFound Not found

swagger:response getDefinitionNotFound
*/
type GetDefinitionNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetDefinitionNotFound creates GetDefinitionNotFound with default headers values
func NewGetDefinitionNotFound() *GetDefinitionNotFound {

	return &GetDefinitionNotFound{}
}

// WithPayload adds the payload to the get definition not found response
func (o *GetDefinitionNotFound) WithPayload(payload *models.ReturnCode) *GetDefinitionNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get definition not found response
func (o *GetDefinitionNotFound) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDefinitionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDefinitionInternalServerErrorCode is the HTTP code returned for type GetDefinitionInternalServerError
const GetDefinitionInternalServerErrorCode int = 500

/*GetDefinitionInternalServerError Internal server error

swagger:response getDefinitionInternalServerError
*/
type GetDefinitionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetDefinitionInternalServerError creates GetDefinitionInternalServerError with default headers values
func NewGetDefinitionInternalServerError() *GetDefinitionInternalServerError {

	return &GetDefinitionInternalServerError{}
}

// WithPayload adds the payload to the get definition internal server error response
func (o *GetDefinitionInternalServerError) WithPayload(payload *models.ReturnCode) *GetDefinitionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get definition internal server error response
func (o *GetDefinitionInternalServerError) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDefinitionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetDefinitionDefault Unexpected error

swagger:response getDefinitionDefault
*/
type GetDefinitionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetDefinitionDefault creates GetDefinitionDefault with default headers values
func NewGetDefinitionDefault(code int) *GetDefinitionDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDefinitionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get definition default response
func (o *GetDefinitionDefault) WithStatusCode(code int) *GetDefinitionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get definition default response
func (o *GetDefinitionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get definition default response
func (o *GetDefinitionDefault) WithPayload(payload *models.ReturnCode) *GetDefinitionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get definition default response
func (o *GetDefinitionDefault) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDefinitionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
