CREATE TABLE dictionary.userAccounts (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(55) NOT NULL UNIQUE,
  creationTS TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updateTS TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE dictionary.userPasswords (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID INT(11) NOT NULL,
  hashedPassword VARCHAR(255) NOT NULL,
  creationTS TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updateTS TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_password
    FOREIGN KEY (userID)
    REFERENCES dictionary.userAccounts (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
