---
swagger: "2.0"
consumes:
  - application/json
produces:
  - application/json
info:
  title: mad-libs
  version: 0.0.1
  description: Mad Libs dictionary game
schemes:
  - http
basePath: /

paths:
  /ready:
    get:
      tags:
        - ready
      summary: Verify that the API is running and ready to accept requests
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ReturnCode"
        500:
          description: Internal service error
          schema:
            $ref: "#/definitions/ReturnCode"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ReturnCode"
  /definition:
    get:
      tags:
        - definition
      summary: Get the full definition for one word from the entries table
      description: |
        Retrieve a row from the entries table and any other entries of additional
        definitions for the same word.
      parameters:
        - name: word
          type: string
          in: query
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Definition"
        404:
          description: Not found
          schema:
            $ref: "#/definitions/ReturnCode"
        500:
          description: Internal service error
          schema:
            $ref: "#/definitions/ReturnCode"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ReturnCode"

definitions:
  ReturnCode:
    type: object
    properties:
      code:
        type: integer
        readOnly: true
      message:
        type: string
        readOnly: true
  Definition:
    type: object
    properties:
      entries:
        type: array
        items: 
          $ref: "#/definitions/Entry"
  Entry:
    type: object
    properties:
      word:
        type: string
      wordType:
        type: string
      definition: 
        type: string
